source 'https://rubygems.org'

ruby '2.5.7'

gem 'middleman', '~> 4.2'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby, :x64_mingw]
gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw, :x64_mingw]
gem 'middleman-livereload', '~> 3.4', '>= 3.4.6'
gem 'webpacker', '~> 4.x'

gem 'middleman-sprockets', '4.0.0'

source 'https://rails-assets.org' do
  gem 'rails-assets-bootstrap', '1.0.0'
  gem 'rails-assets-jquery', '2.1.1'
end
